version: '3.8'
services:
  app-backend:
    image: ${DOCKERHUB_USERNAME}/app-truyen-backend:latest
    container_name: app-backend  # <-- Đã thêm lại
    restart: always              # <-- Đã thêm lại
    expose:
      - "8080"
    # Lệnh này bảo Docker: "Hãy đọc file .env nằm cùng thư mục và nạp hết vào Container"
    env_file:
      - .env
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=postgres
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_EXPIRATION=86400000
    depends_on:
      - db-novel
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-southeast-1
        awslogs-group: /ecs/app-backend
        awslogs-create-group: "true"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-proxy # <-- Đã thêm lại
    restart: always             # <-- Đã thêm lại
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app-backend
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-southeast-1
        awslogs-group: /ecs/nginx-proxy
        awslogs-create-group: "true"
    networks:
      - app-network

  db-novel:
    image: postgres:15-alpine
    container_name: db-novel    # <-- Đã thêm lại
    restart: always             # <-- Đã thêm lại
    command: postgres -c 'log_min_duration_statement=1000'
    environment:
      - POSTGRES_DB=noveldb
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-southeast-1
        awslogs-group: /ecs/db-novel
        awslogs-create-group: "true"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data_prod: