CREATE TABLE genres
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    name        VARCHAR(100)                            NOT NULL,
    description VARCHAR(255),
    CONSTRAINT pk_genres PRIMARY KEY (id)
);

ALTER TABLE genres
    ADD CONSTRAINT uc_genres_name UNIQUE (name);