events {
    worker_connections 1024;
}

http {
    server {
        listen 80; # Lễ tân đứng ở cổng 80 (Cổng chính)

        location / {
            # Chuyển tiếp lời nhắn vào cho Giám đốc (App)
            # 'app-backend' là tên service trong docker-compose
            proxy_pass http://app-backend:8080;

            # Kèm theo thông tin người gửi để Giám đốc biết
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}