name: CI - Test Code Before Merge

# Chỉ chạy khi có Pull Request mở vào nhánh main
on:
  pull_request:
    branches: [ "main" ]

jobs:
  test-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven' # <--- Trả lời câu 5: Cache giúp chạy nhanh hơn

      - name: Run Unit Tests
        working-directory: ./backend
        run: mvn test # Chỉ chạy test, lỗi thì báo đỏ
        