name: CD - Deploy to AWS EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. Copy file docker-compose.prod.yml lên Server
      - name: Copy docker-compose file to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "docker-compose.prod.yml"
          target: "/home/ubuntu/"

      # 2. SSH vào và Deploy
      - name: SSH and Deploy
        uses: appleboy/ssh-action@v1.0.3
        # QUAN TRỌNG: Map Secrets vào biến môi trường của Step này trước
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }} # Lấy từ GitHub Secret
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          # Danh sách các biến môi trường muốn gửi sang Server (cách nhau dấu phẩy)
          envs: DOCKERHUB_USERNAME,DOCKERHUB_TOKEN,DB_PASSWORD
          script: |
            export DOCKERHUB_USERNAME=$DOCKERHUB_USERNAME
            export DB_PASSWORD=$DB_PASSWORD
            
            cd /home/ubuntu
            # Lúc này trên Server đã có các biến $DB_PASSWORD, $DOCKERHUB_USERNAME
            
            # Login Docker Hub
            echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            
            # 1. Tắt container cũ (Thêm 2>/dev/null để không báo lỗi đỏ nếu chưa có)
            docker-compose -f docker-compose.prod.yml down || true
            
            # 2. Pull Image mới (Dùng dấu gạch ngang docker-compose)
            docker-compose -f docker-compose.prod.yml pull
            
            # 3. Chạy lại (Dùng dấu gạch ngang docker-compose)
            docker-compose -f docker-compose.prod.yml up -d